name: "🚀 Software Project Contribution"
description: "Propose a new software project for FINOS Labs, Incubating, or Graduated stages."
title: "Proposed: [Project Name]"
labels: ["contribution"]
assignees: ["maoo", "TheJuanAndOnly99"]
body:
  - type: markdown
    attributes:
      value: |
        ### Welcome to the FINOS Community! 
        Thank you for your interest in contributing. Please read the instructions below carefully and fill in all required information to help us process your proposal efficiently.

        #### ⚠️ Important Note on Membership
        Only **FINOS members** can propose new projects. Non-members are encouraged to identify a member sponsor during the socialization phase. [See here](https://www.finos.org/membership-benefits#become-a-member) if you are interested in becoming a FINOS member.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Contribution Prerequisites
      options:
        - label: "I confirm I am contributing on behalf of a FINOS member OR I will seek a maintainer from a member during socialization."
        - label: "I have reviewed the [FINOS Contribution Process](https://community.finos.org/docs/governance/software-projects/contribution/)."
        - label: "I have reviewed the [FINOS Project Lifecycle](https://community.finos.org/docs/governance/project-lifecycle) stages."
        - label: "I am familiar with [FINOS Governance](https://community.finos.org/docs/governance) and [Maintainer Responsibilities](https://community.finos.org/docs/finos-maintainers-cheatsheet/)."
    validations:
      required: true

  - type: dropdown
    id: stage
    attributes:
      label: Target Lifecycle Stage
      description: "Which stage are you applying for based on the FINOS Project Lifecycle?"
      options:
        - Labs
        - Incubating
        - Graduated
    validations:
      required: true

  - type: input
    id: member_org_name
    attributes:
      label: FINOS Member Organization Name
      description: "Enter the name of the member organization backing this proposal."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "---"
  

  - type: markdown
    attributes:
      value: "## 1. Project Details"

  - type: input
    id: project_name
    attributes:
      label: Name
      placeholder: "The proposed project common name"
    validations:
      required: true

  - type: input
    id: project_slug
    attributes:
      label: Slug
      description: "Must be kebab-case (e.g., my-project-name)"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "1-2 sentence summary of what the software does."
    validations:
      required: true

  - type: textarea
    id: business_problem
    attributes:
      label: Business Problem & Solution
      description: "Describe the specific problem this solves for Financial Services and how this software addresses it."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "---"

  - type: markdown
    attributes:
      value: "## 2. MAINTAINER TEAM"

  - type: textarea
    id: maintainers
    attributes:
      label: Maintainer Team
      description: "Identify the core team. At least one maintainer must be from a FINOS member org."
      value: |
        | Name | Affiliation | Email | GitHub Username |
        | :--- | :--- | :--- | :--- |
        | John Example |Example LTD | john@example.com | @johnexampleabc |
        | Jane Example | Example LTD | jane@example.com | @janeexamplexyz |

    validations:
      required: true

  - type: markdown
    attributes:
      value: "---"

  - type: markdown
    attributes:
      value: "## 3. COMPLIANCE CONFIRMATION"

  - type: checkboxes
    id: compliance_confirmation
    attributes:
      label: Compliance & Requirements Agreement
      description: "Confirm you have read and agree to the following [FINOS Requirements](https://community.finos.org/docs/governance/Software-Projects/Contribution-Compliance-Requirements)."
      options:
        - label: " I understand that all maintainers and contributors will need to be covered by a [Contributors License Agreement](https://community.finos.org/docs/governance/software-projects/contribution-compliance-requirements/#contributor-license-agreement) before being able to contribute."
          required: true
        - label: "I confirm that software will be covered by the [Apache 2.0. License](https://community.finos.org/docs/governance/software-projects/contribution-compliance-requirements/#license-information) and any [Third-Party code is compatible](https://community.finos.org/docs/governance/software-projects/contribution-compliance-requirements/#third-party-code-compliance)."
          required: true
        - label: "I have selected the appropriate [lifecycle stage](https://community.finos.org/docs/governance/project-lifecycle) based on that stages requirements. I agree and commit to to the Acceptance & Maintenance Requirements for my target stage."
          required: true

  - type: checkboxes
    id: socialization_confirm
    attributes:
      label: Socialization Acknowledgement
      options:
        - label: "I understand I may need to socialize this proposal to community@finos.org before a TOC review to guage community interest."
          required: true

  - type: markdown
    attributes:
      value: "---"

  - type: markdown
    attributes:
      value: |
        ---
        ### ℹ️ Next Steps for Advanced Stages
        If you have applied for the **Incubating** or **Graduated** stage, please note that these require a more detailed vetting process. After our initial review of this proposal, a member of the FINOS team will follow up on this issue with next steps and a link to a stage-specific sub-issue form to collect further technical and community evidence.

  - type: markdown
    attributes:
      value: "---"

  - type: markdown
    attributes:
      value: "## 4. INTERNAL OPERATIONS (FINOS Staff Only)"

  - type: checkboxes
    id: internal_workflow
    attributes:
      label: Operational Completion
      description: "This checkbox is for FINOS Staff use only."
      options:
        - label: "I confirm that all preliminary internal FINOS reviews and workflow tasks have been completed."
    validations:
      required: false
